[Variables]

;Game setting for which game to find matches from
Game = dota2
;Only certain games are supported
;Possible Game List (all game names are casesenstive):
;dota2
;counterstrike
;hearthstone

;Maximum number of upcoming matches to display
maxNumUpcomingMatches = 6
;default = 6
;use -1 to read all upcoming matches (on first page of gosugamer website)

matchFontSize = 8
;default = 8
matchFontColor = 0, 0, 0, 255
;default = 0, 0, 0, 255 (white)
matchFontFace = Times New Roman
;default = Times New Roman
matchStringStyle = Normal
;default = Normal